### ISSUE TITLE
Change Header UI

### ISSUE THREAD

**Issue by madalenamakiesse** [aman5062/helpdesk2#23]
Hello @aman5062 , I propose to let me change the header UI.
@aosccode
This is my solution:

![image](https://github.com/aman5062/helpdesk2/assets/62503320/a02fdd4e-5447-4cba-9d67-bdfe219e76ef)

![image](https://github.com/aman5062/helpdesk2/assets/62503320/2615f38c-cbd2-430c-98e9-7511914a6d92)

**Comment by antonio-pedro99** [comment]
Boas @madalenamakiesse, obrigado pela participação e teu trabalho árduo :)

Antes de levantar uma PR, é importante saber se a Issue foi aceite ou nāo. 
Vamos esperar o maintainer deste projeto fazer triagem e aprovar a tua sugestão, depois disso podes criar uma PR :) 

Happy backing

**Comment by aman5062** [comment]
@madalenamakiesse You can Change it. Please be sure about the mobile responsiveness.
